version: '3.9'

services:
  db:
    image: postgres:17
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: shepherdstaff
      TZ: GMT+8
    ports:
      - "5432:5432"